assetic:
    bundles: ['AppBundle', 'IhsanSimpleAdminBundle']
    filters:
        cssrewrite: ~
        closure:
            jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        yui_css:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.8.jar"

framework:
    translator: { fallbacks: ["%locale%"] }

knp_paginator:
    page_range: 5
    default_options:
        page_name: page
        sort_field_name: sort
        sort_direction_name: direction
        distinct: true

knp_menu:
    twig:
        template: knp_menu.html.twig
    templating: false
    default_renderer: twig

ihsan_simple_admin:
    app_title: 'Ihsanuddin Skeleton'
    per_page: 10
    identifier: 'id'
    date_time_format: 'd-m-Y' #php date time format
    menu: 'ihsan_simple_admin_main_menu'
    profile_fields: ['username', 'email', 'roles']
    filter: 'name'
    translation_domain: 'IhsanSimpleAdminBundle'
    security:
        user:
            form_class: ihsan.simple_admin.user_form
            entity_class: Ihsan\SimpleAdminBundle\Entity\User
    grid_action:
        show: true
        edit: true
        delete: true
    themes:
        dashboard: 'IhsanSimpleAdminBundle:Index:index.html.twig'
        form_theme: 'IhsanSimpleAdminBundle:Form:fields.html.twig'
        pagination: 'IhsanSimpleAdminBundle:Layout:pagination.html.twig'

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Ihsan\SimpleAdminBundle\Entity\User